name: scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches: [ main ]
permissions:
  contents: read
  id-token: write
  pull-requests: read
  security-events: write
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
