name: preflight
on: [push, pull_request]
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate workflow YAMLs
        run: |
          python - << 'PY'
          import os, sys
          try:
            import yaml
          except ImportError:
            import subprocess; subprocess.check_call([sys.executable, "-m", "pip", "install", "pyyaml"])
            import yaml
          for root,_,files in os.walk('.github/workflows'):
            for f in files:
              if f.endswith(('.yml','.yaml')):
                with open(os.path.join(root,f),'r',encoding='utf-8') as fh:
                  yaml.safe_load(fh.read())
          print("All workflow YAMLs parsed successfully.")
          PY
